In [1]:
#Creating the Sales DataFrame
import pandas as pd

data = {
    '2014': [100.5, 150.8, 200.9, 30000, 40000],
    '2015': [12000, 18000, 22000, 30000, 45000],
    '2016': [20000, 50000, 70000, 100000, 125000],
    '2017': [50000, 60000, 70000, 80000, 90000]
}

index_labels = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

Sales = pd.DataFrame(data, index=index_labels)
Sales


2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000

In [3]:
#Operations on the Sales DataFrame
#a) Row labels
print("Row Labels:", Sales.index.tolist())

Row Labels: ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']


In [4]:
#b) Column labels
print("Column Labels:", Sales.columns.tolist())

Column Labels: ['2014', '2015', '2016', '2017']


In [5]:
#c) Data types
print("Data Types:\n", Sales.dtypes)

Data Types:
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object


In [6]:
#d) Dimensions, shape, size, values
print("Dimensions:", Sales.ndim)
print("Shape:", Sales.shape)
print("Size:", Sales.size)
print("Values:\n", Sales.values)

Dimensions: 2
Shape: (5, 4)
Size: 20
Values:
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [7]:
#e) Last two rows
print("Last 2 Rows:\n", Sales.tail(2))

Last 2 Rows:
            2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000


In [8]:
#f) First two columns
print("First 2 Columns:\n", Sales.iloc[:, :2])

First 2 Columns:
             2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000


In [9]:
#g) Create Sales2 using dictionary
data2 = {
    '2018': {
        'Madhu': 160000,
        'Kusum': 110000,
        'Kinshuk': 500000,
        'Ankit': 340000,
        'Shruti': 900000
    }
}
Sales2 = pd.DataFrame(data2)
print("Sales2:\n", Sales2)

Sales2:
            2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000


In [10]:
#h) Check if Sales2 is empty
print("Is Sales2 empty?", Sales2.empty)

Is Sales2 empty? False


In [11]:
#Operations on DataFrames
# a) Append Sales2
Sales = pd.concat([Sales, Sales2], axis=1)
print("Sales after appending Sales2:\n", Sales)

Sales after appending Sales2:
             2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000


In [12]:
# b) Transpose Sales
Sales_T = Sales.T
print("Transposed Sales:\n", Sales_T)

Transposed Sales:
          Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0


In [13]:
# c) Sales in 2017
print("Sales in 2017:\n", Sales['2017'])

Sales in 2017:
 Madhu      50000
Kusum      60000
Kinshuk    70000
Ankit      80000
Shruti     90000
Name: 2017, dtype: int64


In [14]:
# d) Sales by Madhu and Ankit in 2017 and 2018
print("Sales by Madhu and Ankit in 2017 & 2018:\n", Sales.loc[['Madhu', 'Ankit'], ['2017', '2018']])


Sales by Madhu and Ankit in 2017 & 2018:
         2017    2018
Madhu  50000  160000
Ankit  80000  340000


In [15]:
# e) Sales by Shruti in 2016
print("Shruti's 2016 Sales:", Sales.loc['Shruti', '2016'])

Shruti's 2016 Sales: 125000


In [16]:
# f) Add Sumeet
Sales.loc['Sumeet'] = [196.2, 37800, 52000, 78438, 38852]
print("After adding Sumeet:\n", Sales)

After adding Sumeet:
             2014     2015      2016     2017      2018
Madhu      100.5  12000.0   20000.0  50000.0  160000.0
Kusum      150.8  18000.0   50000.0  60000.0  110000.0
Kinshuk    200.9  22000.0   70000.0  70000.0  500000.0
Ankit    30000.0  30000.0  100000.0  80000.0  340000.0
Shruti   40000.0  45000.0  125000.0  90000.0  900000.0
Sumeet     196.2  37800.0   52000.0  78438.0   38852.0


In [17]:
# g) Delete year 2014
Sales = Sales.drop(columns='2014')
print("After deleting 2014 column:\n", Sales)

After deleting 2014 column:
             2015      2016     2017      2018
Madhu    12000.0   20000.0  50000.0  160000.0
Kusum    18000.0   50000.0  60000.0  110000.0
Kinshuk  22000.0   70000.0  70000.0  500000.0
Ankit    30000.0  100000.0  80000.0  340000.0
Shruti   45000.0  125000.0  90000.0  900000.0
Sumeet   37800.0   52000.0  78438.0   38852.0


In [18]:
# h) Delete Kinshuk
Sales = Sales.drop(index='Kinshuk')
print("After deleting Kinshuk:\n", Sales)

After deleting Kinshuk:
            2015      2016     2017      2018
Madhu   12000.0   20000.0  50000.0  160000.0
Kusum   18000.0   50000.0  60000.0  110000.0
Ankit   30000.0  100000.0  80000.0  340000.0
Shruti  45000.0  125000.0  90000.0  900000.0
Sumeet  37800.0   52000.0  78438.0   38852.0


In [19]:
# i) Rename Ankit to Vivaan, Madhu to Shailesh
Sales.rename(index={'Ankit': 'Vivaan', 'Madhu': 'Shailesh'}, inplace=True)
print("After renaming:\n", Sales)

After renaming:
              2015      2016     2017      2018
Shailesh  12000.0   20000.0  50000.0  160000.0
Kusum     18000.0   50000.0  60000.0  110000.0
Vivaan    30000.0  100000.0  80000.0  340000.0
Shruti    45000.0  125000.0  90000.0  900000.0
Sumeet    37800.0   52000.0  78438.0   38852.0


In [20]:
# j) Update Shailesh’s 2018 sales to 100000
Sales.loc['Shailesh', '2018'] = 100000
print("After updating Shailesh's 2018 sales:\n", Sales)

After updating Shailesh's 2018 sales:
              2015      2016     2017      2018
Shailesh  12000.0   20000.0  50000.0  100000.0
Kusum     18000.0   50000.0  60000.0  110000.0
Vivaan    30000.0  100000.0  80000.0  340000.0
Shruti    45000.0  125000.0  90000.0  900000.0
Sumeet    37800.0   52000.0  78438.0   38852.0


In [24]:
# k) Save to CSV (without row and column labels)
Sales.to_csv('SalesFigures.csv', index=False, header=False)

In [23]:
# l) Read from CSV and update labels
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)
SalesRetrieved.index = Sales.index
SalesRetrieved.columns = Sales.columns
print("SalesRetrieved:\n", SalesRetrieved)

SalesRetrieved:
              2015      2016     2017      2018
Shailesh  12000.0   20000.0  50000.0  100000.0
Kusum     18000.0   50000.0  60000.0  110000.0
Vivaan    30000.0  100000.0  80000.0  340000.0
Shruti    45000.0  125000.0  90000.0  900000.0
Sumeet    37800.0   52000.0  78438.0   38852.0


In [26]:
#a) Create the DataFrame
import pandas as pd

# Initial data
data = {
    'Item': ['TV', 'TV', 'TV', 'AC'],
    'Company': ['LG', 'VIDEOCON', 'LG', 'SONY'],
    'Rupees': [12000, 10000, 15000, 14000],
    'USD': [700, 650, 800, 750]
}

df = pd.DataFrame(data)
df

Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750

In [28]:
# b) Add New Rows
# New rows to be added
new_rows = pd.DataFrame({
    'Item': ['Fridge', 'Washing Machine'],
    'Company': ['SAMSUNG', 'WHIRLPOOL'],
    'Rupees': [22000, 18000],
    'USD': [950, 870]
})

# Append to original DataFrame
df = pd.concat([df, new_rows], ignore_index=True)
df


Item    Company  Rupees  USD
0               TV         LG   12000  700
1               TV   VIDEOCON   10000  650
2               TV         LG   15000  800
3               AC       SONY   14000  750
4           Fridge    SAMSUNG   22000  950
5  Washing Machine  WHIRLPOOL   18000  870

In [29]:
#c) Max price of LG TV
lg_tv_max = df[(df['Item'] == 'TV') & (df['Company'] == 'LG')]['Rupees'].max()
print("Maximum price of LG TV:", lg_tv_max)

Maximum price of LG TV: 15000


In [31]:
#d) Sum of all products (in Rupees)
total_sum = df['Rupees'].sum()
print("Total Sum of Rupees:", total_sum)


Total Sum of Rupees: 91000


In [32]:
#e) Median of USD of Sony products
sony_median = df[df['Company'] == 'SONY']['USD'].median()
print("Median USD of SONY products:", sony_median)

Median USD of SONY products: 750.0


In [34]:
import pandas as pd
import numpy as np

# a) To create the above DataFrame:
data = {
    'Name': ['Aparna', 'Pankaj', 'Ram', 'Ramesh', 'Naveen', 'Krrishnav', 'Bhawna'],
    'Degree': ['MBA', 'BCA', 'M.Tech', 'MBA', np.nan, 'BCA', 'MBA'],
    'Score': [90.0, np.nan, 80.0, 98.0, 97.0, 78.0, 89.0]
}
df = pd.DataFrame(data)
print(df)

        Name  Degree  Score
0     Aparna     MBA   90.0
1     Pankaj     BCA    NaN
2        Ram  M.Tech   80.0
3     Ramesh     MBA   98.0
4     Naveen     NaN   97.0
5  Krrishnav     BCA   78.0
6     Bhawna     MBA   89.0


In [35]:
# b) To print the Degree and maximum marks in each stream:
print(df.groupby('Degree')['Score'].max())

Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64


In [36]:
# c) To fill the NaN with 76:
df_filled = df.fillna(76)
print(df_filled)

        Name  Degree  Score
0     Aparna     MBA   90.0
1     Pankaj     BCA   76.0
2        Ram  M.Tech   80.0
3     Ramesh     MBA   98.0
4     Naveen      76   97.0
5  Krrishnav     BCA   78.0
6     Bhawna     MBA   89.0


In [37]:
# d) To set the index to Name:
df_indexed = df.set_index('Name')
print(df_indexed)

           Degree  Score
Name                    
Aparna        MBA   90.0
Pankaj        BCA    NaN
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen        NaN   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0


In [38]:
# e) To display the name and degree wise average marks of each student:
print(df.groupby(['Name', 'Degree'])['Score'].mean())

Name       Degree
Aparna     MBA       90.0
Bhawna     MBA       89.0
Krrishnav  BCA       78.0
Pankaj     BCA        NaN
Ram        M.Tech    80.0
Ramesh     MBA       98.0
Name: Score, dtype: float64


In [39]:
# f) To count the number of students in MBA:
print((df['Degree'] == 'MBA').sum())

3


In [40]:
# g) To print the mode marks BCA:
print(df[df['Degree'] == 'BCA']['Score'].mode())

0    78.0
Name: Score, dtype: float64
